### ISSUE TITLE
标准库++正则表达式库

### ISSUE THREAD

**Issue by TheMorbidArk** [TheMorbidArk/Tiderip#10]
### GNU regex 是GNU提供的跨平台的 POSIX 正则表达式库
`#include<regex.h>`
- 便于GNU GCC环境下开发
- 易于移植至其他平台

[MSVC下使用gnu regex](https://blog.csdn.net/10km/article/details/121182327)

### TODO
- [x] 标准库增加 Regex类
- [x] 使能 Regex类 正常解析正则表达式

**Comment by TheMorbidArk** [comment]
### 初步实现 Regex

初步引入<regex.h>，可通过`setPattern(_)`方法设置正则表达式，`exec(_)`方法进行正则匹配。

其中，`exec(_)`方法匹配成功会返回第一个匹配字符串，匹配失败则返回`null`。

使用示例：

```c
Regex.setPattern("(^((22[0-3]丨2[0-1][0-9]|[0-1][0-9][0-9]|0[1 -9][0-9]|([0-9])]{1,2})([.](25[0-5]|2[0-4][0-9]|[0-1][0-9][0-9]|0[1 -9][0-9]|([0-9])]{1,2})){3})$)")
    
Tide ansStr_1 = Regex.exec("124.124.124.124")
if(ansStr_1 != null){
	System.println(ansStr_1)
} else {
    System.println("Matching Failed")
}

Tide ansStr_2 = Regex.exec("1234.124.124.124")
if(ansStr_2 != null){
	System.println(ansStr_2)
} else {
    System.println("Matching Failed")
}
```

运行结果:

> 124.124.124.124
> Matching Failed

**Comment by TheMorbidArk** [comment]
### The Next  TODO

进一步优化Regex接口

- [ ] `Regex`类增加`匹配结果最大允许数`和`匹配结果在待匹配串中的下标范围`属性
- [ ] `setPattern(_)`接口进一步封装为`set(_, ...)`接口
- [ ] 使用`set(_, ...)`接口可配置正则表达式、匹配结果最大允许数、匹配结果在待匹配串中的下标范围

**期望达成效果：**

```c
Regex.set("(^((22[0-3]丨2[0-1][0-9]|[0-1][0-9][0-9]|0[1 -9][0-9]|([0-9])]{1,2})([.](25[0-5]|2[0-4][0-9]|[0-1][0-9][0-9]|0[1 -9][0-9]|([0-9])]{1,2})){3})$)"，
          1,
          1)
    
Tide ansStr_1 = Regex.exec("124.124.124.124")
if(ansStr_1 != null){
	System.println(ansStr_1)
} else {
    System.println("Matching Failed")
}

```

**Comment by TheMorbidArk** [comment]
### 优化Regex库的使用
- 使能通过`set()`函数进行配置
- 使能进行多次匹配

**使用示例：**
```c

Regex.set("(^((22[0-3]丨2[0-1][0-9]|[0-1][0-9][0-9]|0[1 -9][0-9]|([0-9])]{1,2})([.](25[0-5]|2[0-4][0-9]|[0-1][0-9][0-9]|0[1 -9][0-9]|([0-9])]{1,2})){3})$)",
          3,
          false,
          true)

System.println(Regex.getPattern())
System.println(Regex.getTimes())
System.println(Regex.getFlagICASE())
System.println(Regex.getflagNEWLINE())

Tide ansStr_1 = Regex.exec("124.124.124.124\n192.168.123.124\n127.124.144.164")
if(ansStr_1 != null){
	System.println(ansStr_1)
} else {
    System.println("Matching Failed")
}

```
**运行结果：**
```c
(^((22[0-3]丨2[0-1][0-9]|[0-1][0-9][0-9]|0[1 -9][0-9]|([0-9])]{1,2})([.](25[0-5]|2[0-4][0-9]|[0-1][0-9][0-9]|0[1 -9][0-9]|([0-9])]{1,2})){3})$)
3
false
true
[124.124.124.124,192.168.123.124,127.124.144.164]
```
